name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions ğŸš€

on:
  push:
    branches: [ main ]

  #workflow_dispatch:

env:
  applicationfolder: spring-boot-hello-world-example
  AWS_REGION: us-east-1
  S3BUCKET: bucket-767x60opu87j

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Code checkout
        uses: actions/checkout@v4
      - name: Java setup
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: 17
      - name: Project build
        run: mvn clean install -Dskiptests
      - name: Dockerhub Login
        run: docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PASSWORD}}
      - name: Docker image build
        run: docker build -t .
      - name: Docker image push
        run: docker push .

  ##Explore-GitHub-Actions:
    ##runs-on: ubuntu-latest
    ##steps:
      ##- run: echo "ğŸ‰ The job was automatically triggered by a ${{ github.event_name }} event."
      ##- run: echo "ğŸ§ This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      ##- run: echo "ğŸ” The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      ##- name: Check out repository code
      ##  uses: actions/checkout@v4
      ##- run: echo "ğŸ’¡ The ${{ github.repository }} repository has been cloned to the runner."
      ##- run: echo "ğŸ–¥ï¸ The workflow is now ready to test your code on the runner."
      ##- name: List files in the repository
      ##  run: |
      ##    ls ${{ github.workspace }}
      ##- run: echo "ğŸ This job's status is ${{ job.status }}."*/
